### ISSUE TITLE
[feature request] Using circleCI to split test dimensions

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1008]
### Ⅰ. Issue Description

We could use circleCI to split tests into several small parts. And every part could show its name to make itself much more readable for users.  Currently Pouch has used cirlceCI for **markdown file validation**, and we wish to support using circleCI to run **unit test**. Others(integration test and cri-tools test) still use travisCI to run test.

I would like to take project https://github.com/docker/cli as an example, in which CI test via CircleCI shows like the following:

![image](https://user-images.githubusercontent.com/9465626/38086520-41e2846c-3387-11e8-9c0c-a13bb3568380.png)

How to achieve this?
Look file https://github.com/docker/cli/blob/master/circle.yml, we could write file like:

```
version: 2

jobs:

  lint:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker:
            reusable: true
            exclusive: false
      - run:
          command: docker version
      - run:
          name: "Lint"
          command: |
            dockerfile=dockerfiles/Dockerfile.lint
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-linter:$CIRCLE_BUILD_NUM .
            docker run --rm cli-linter:$CIRCLE_BUILD_NUM
  cross:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    parallelism: 3
    steps:
      - checkout
      - setup_remote_docker:
            reusable: true
            exclusive: false
      - run:
          name: "Cross"
      .......
  
  test:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker:
            reusable: true
            exclusive: false
      - run:
          name: "Unit Test with Coverage"
          command: |
            dockerfile=dockerfiles/Dockerfile.dev
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-builder:$CIRCLE_BUILD_NUM .
            docker run --name \
                test-$CIRCLE_BUILD_NUM cli-builder:$CIRCLE_BUILD_NUM \
                make test-coverage
      - run:
          name: "Upload to Codecov"
          command: |
            docker cp \
                test-$CIRCLE_BUILD_NUM:/go/src/github.com/docker/cli/coverage.txt \
                coverage.txt
   .......
  validate:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
   .......
  shellcheck:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
   .......
  version: 2
  ci:
    jobs:
      - lint
      - cross
      - test
      - validate
      - shellcheck
```

Last but not the least, we still needs the codecov report for unit test.
