### ISSUE TITLE
[bug] conflict exists in pid-limit config of a container in CLI and swagger.yml

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2483]
### Ⅰ. Issue Description

In swagger, there is the definition of `PidLimit` of `Resource` of a container : 

```
      PidsLimit:
        description: |
          Tune a container's pids limit. Set -1 for unlimited. Only on Linux 4.4 does this parameter support.
        type: "integer"
        format: "int64"
        x-nullable: false
        x-omitempty: false
```

There it say that `-1 for unlimited`. 

While in the https://github.com/alibaba/pouch/blob/master/cli/common_flags.go#L100, we have 

```
	flagSet.Int64Var(&c.pidsLimit, "pids-limit", 0, "Set container pids limit")
```

The default value is 0. Are the `0` and `-1` conflict.

In my opinion, the default value should be `-1` for ulimited.

WDYT? @Ace-Tang
