### ISSUE TITLE
[feature-request] Add Tini as init process to reap zombies and perform signal forwarding.

### ISSUE THREAD

**Issue by CodeJuan** [alibaba/pouch#2526]
## Why you need it?
We've found that a lot of Pouch user have problem about the zombie reaping. 
So I think we should add a default `init` process to reap zombies and perform signal forwarding.

## How it could be?
[Tini](https://github.com/krallin/tini) is a simplest init for container.

> All Tini does is spawn a single child (Tini is meant to be run in a container), and wait for it to exit all the while reaping zombies and performing signal forwarding.
Using Tini has several benefits:
    - It protects you from software that accidentally creates zombie processes, which can (over time!) starve your entire system for PIDs (and make it unusable).
    - It ensures that the default signal handlers work for the software you run in your Docker image. For example, with Tini, SIGTERM properly terminates your process even if you didn't explicitly install a signal handler for it.
    - It does so completely transparently! Docker images that work without Tini will work with Tini without any changes.

**Comment by ZYecho** [comment]
@CodeJuan Hi, can you explain why chose` tini`, I find that there's also other choice, such as [dumb-init](https://github.com/Yelp/dumb-init)

**Comment by CodeJuan** [comment]
> @CodeJuan Hi, could you explain why chose `tini`? I find that there's also other choice, such as [dumb-init](https://github.com/Yelp/dumb-init).
> In addition, what's this feature request different with pouch already supported feature -> rich-mode?

@ZYecho Some docker user use `--init` to create a container with init process, for example, [nvidia-gpu-compose.yml](https://gitlab.com/nvidia/samples/blob/master/mps/docker-compose.yml) set `init=true` to create a container with init process.
```yml
    mps-daemon:
        image: nvidia/mps
        container_name: mps-daemon
        restart: on-failure
        depends_on:
          - exclusive-mode
        environment:
          - "NVIDIA_VISIBLE_DEVICES"
          - "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE"
        init: true
```
It's similar to `rich-mode`, and dumb-init is a good choice too. We should Make compatible for `--init` feature, no matter what kind of implementation, such as `tini`, `dumb-init` and `systemd` is ok.
