### ISSUE TITLE
[bug] definition of rich/rich-mode should not both in struct ContainerConfig and HostConfig

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#826]
### Ⅰ. Issue Description
Currently, in rich/rich-mode field are defined both in struct ContainerConfig and HostConfig, please refer https://github.com/alibaba/pouch/blob/master/apis/swagger.yml

From the description of this two structures, these two structs are conflict:
```
ContainerConfig:

    type: "object"

    description: "Configuration for a container that is portable between hosts"

HostConfig:

    description: "Container configuration that depends on the host we are running on"
```

So, remove the definition in HostConfig.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
